Merge release to main
microsoft/CLRInstrumentationEngine pull request #418
Opened 2021-07-20 05:20 UTC by WilliamXieMSFT

2021-07-21 17:06 UTC, delmyers requested changes

2021-07-21 17:06 UTC, delmyers commented on CHANGELOG.md
> +  + Remove PathCch functions in order to support Win7
I would wait until the other two PRs into release are finished.

2021-07-21 23:49 UTC, delmyers approved these changes

2021-07-22 23:02 UTC, WilliamXieMSFT commented
/azp run

2021-07-22 23:47 UTC, WilliamXieMSFT commented
Seems changes in main conflict with release:

../../InstrumentationEngine.Lib/libInstrumentationEngine.Lib.a(InstrumentationMethod.cpp.o): In function `MicrosoftInstrumentationEngine::CInstrumentationMethod::InitializeCore(bool)':
/root/ClrInstrumentationEngine/src/InstrumentationEngine.Lib/./../Common.Headers/StringUtils.h:74: undefined reference to `PathAppendW'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

2021-08-03 17:11 UTC, WilliamXieMSFT commented
/azp run

2021-08-04 22:06 UTC, merged